# Generated by Django 6.1.1 on 2026-10-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_detail',
            fields=[
                ('vehicle_number', models.CharField(max_length=8)),
                ('company', models.CharField(max_length=14)),
                ('year', models.IntegerField()),
                ('phone_number', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('owner_name', models.CharField(max_length=30)),
            ],
        ),
    ]
